name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - release*

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*


env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: wisdomchain/wdc_core
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/


  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-               
      - name: Build image
        run: bash wisdom-core/src/main/docker/core_v2/build-docker.sh
        
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u wisdomchain --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$IMAGE_NAME
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "release" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Log into ali registry
        run: echo "${{ secrets.ALI_DOCKER_PASSWORD }}" | docker login registry.cn-hangzhou.aliyuncs.com -u github@1731051433877231 --password-stdin

      - name: Push image to ali
        run: |
          IMAGE_ID=$IMAGE_NAME
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "release" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION    
          docker tag $IMAGE_NAME registry.cn-hangzhou.aliyuncs.com/wisdomchain/wdc_core:$VERSION
          docker push registry.cn-hangzhou.aliyuncs.com/wisdomchain/wdc_core:$VERSION
